name: Rust

on:
  push:
    branches: [ "rewrite-backend" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      fail-fast: false
      matrix: 
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
        - uses: actions/checkout@v3
        - name: setup rust cache
          uses: Swatinem/rust-cache@v2
          with:
            workspaces: backend -> target
        - name: compile project
          working-directory: ./backend
          run: cargo build
        - name: Archive binaries
          uses: actions/upload-artifact@v3
          with:
            name: ${{ matrix.platform }} binaries
            path: |
              backend/target/release/api
              backend/target/release/api.exe
            
    
